"""Career Pathway labels used by NYUAD Handshake Collections.

All four labels MUST match exactly what exists in Handshake – the agent
searches for them by this text in the Labels dropdown.
"""

from __future__ import annotations

from dataclasses import dataclass


HEALTH = "nyuad health, science, and engineering"
MEDIA = "nyuad media, arts, and communications"
SOCIAL = "nyuad social impact and global affairs"
TECH = "nyuad technology, business, and innovation"


ALL_LABELS: tuple[str, ...] = (HEALTH, MEDIA, SOCIAL, TECH)


@dataclass(frozen=True)
class Pathway:
    label: str
    majors: tuple[str, ...]
    keywords: tuple[str, ...]


PATHWAYS: tuple[Pathway, ...] = (
    Pathway(
        label=TECH,
        majors=(
            "computer science",
            "computer engineering",
            "electrical engineering",
            "mechanical engineering",
            "civil engineering",
            "general engineering",
            "engineering",
            "economics",
            "business",
            "business administration",
            "finance",
            "accounting",
            "mathematics",
            "applied mathematics",
            "data science",
            "interactive media",
            "management",
        ),
        keywords=(
            "software",
            "software engineer",
            "developer",
            "full stack",
            "full-stack",
            "frontend",
            "backend",
            "devops",
            "cloud",
            "aws",
            "azure",
            "gcp",
            "kubernetes",
            "data",
            "data analyst",
            "data analytics",
            "data scientist",
            "machine learning",
            "artificial intelligence",
            " ai ",
            " ai/",
            "ai/ml",
            "ml ",
            "llm",
            "nlp",
            "startup",
            "startups",
            "consulting",
            "consultant",
            "strategy",
            "management consulting",
            "corporate",
            "product manager",
            "product management",
            "product",
            "finance",
            "financial",
            "banking",
            "investment",
            "private equity",
            "venture capital",
            "trading",
            "quant",
            "accounting",
            "marketing",
            "sales",
            "business development",
            "operations",
            "analyst",
            "supply chain",
            "logistics",
            "fintech",
            "blockchain",
            "crypto",
            "web3",
            "saas",
            "android",
            "ios",
            "mobile",
            "python",
            "java",
            "c++",
            "javascript",
            "typescript",
            "react",
            "node",
            "sql",
            "database",
            "cybersecurity",
            "information security",
            "it ",
            "information technology",
            "entrepreneur",
            "entrepreneurship",
            "hardware",
            "robotics",
            "automation",
            "industry",
            "manufacturing",
        ),
    ),
    Pathway(
        label=HEALTH,
        majors=(
            "biology",
            "chemistry",
            "biochemistry",
            "bioengineering",
            "biomedical",
            "physics",
            "mathematics",
            "pre-med",
            "pre-health",
            "neuroscience",
            "psychology",
            "environmental",
            "environmental studies",
            "public health",
        ),
        keywords=(
            "lab",
            "laboratory",
            "research assistant",
            "research scientist",
            "wet lab",
            "clinical",
            "clinic",
            "hospital",
            "medical",
            "medicine",
            "physician",
            "nurse",
            "nursing",
            "healthcare",
            "health care",
            "public health",
            "biotech",
            "biotechnology",
            "pharma",
            "pharmaceutical",
            "pharmacology",
            "drug discovery",
            "genomics",
            "genetics",
            "genome",
            "molecular",
            "cell biology",
            "microbiology",
            "epidemiology",
            "environmental",
            "sustainability",
            "climate",
            "ecology",
            "conservation",
            "renewable",
            "neuroscience",
            "psychology",
            "mental health",
            "chemistry",
            "physics",
            "biology",
            "bioinformatics",
            "clinical trial",
            "patient",
            "therapeutic",
            "diagnostics",
            "fda",
            "who ",
        ),
    ),
    Pathway(
        label=SOCIAL,
        majors=(
            "political science",
            "legal studies",
            "law",
            "social research and public policy",
            "srpp",
            "history",
            "philosophy",
            "economics",
            "anthropology",
            "sociology",
        ),
        keywords=(
            "policy",
            "public policy",
            "law firm",
            "legal",
            "law",
            "paralegal",
            "attorney",
            "litigation",
            "ngo",
            "non-profit",
            "nonprofit",
            "non profit",
            "government",
            "governmental",
            "public sector",
            "civil society",
            "advocacy",
            "human rights",
            "diplomacy",
            "diplomat",
            "united nations",
            "un ",
            "unicef",
            "unhcr",
            "unesco",
            "world bank",
            "imf",
            "international relations",
            "global affairs",
            "foreign affairs",
            "geopolitics",
            "social impact",
            "development",
            "humanitarian",
            "refugee",
            "gender",
            "equity",
            "equality",
            "justice",
            "community",
            "civic",
            "think tank",
            "regulatory",
            "compliance",
            "lobby",
            "election",
            "parliament",
            "ministry",
            "embassy",
        ),
    ),
    Pathway(
        label=MEDIA,
        majors=(
            "theater",
            "theatre",
            "film",
            "film and new media",
            "music",
            "visual arts",
            "art history",
            "literature",
            "creative writing",
            "writing",
            "communications",
            "interactive media",
            "arab crossroads",
        ),
        keywords=(
            "design",
            "designer",
            "graphic design",
            "ux",
            "ui",
            "ux/ui",
            "user experience",
            "user interface",
            "creative",
            "storytelling",
            "storyteller",
            "short-form",
            "short form",
            "long-form",
            "long form",
            "journalism",
            "journalist",
            "editor",
            "editorial",
            "writer",
            "writing",
            "copywriter",
            "copywriting",
            "content creator",
            "content",
            "social media",
            "media",
            "film",
            "filmmaker",
            "filmmaking",
            "video",
            "videography",
            "photography",
            "photographer",
            "animation",
            "animator",
            "illustrator",
            "illustration",
            "theater",
            "theatre",
            "performing arts",
            "performance",
            "music",
            "musician",
            "composer",
            "producer",
            "production assistant",
            "broadcast",
            "tv ",
            "radio",
            "podcast",
            "museum",
            "gallery",
            "curator",
            "art ",
            "arts",
            "artist",
            "fashion",
            "advertising",
            "ad agency",
            "public relations",
            "pr ",
            "branding",
            "brand",
            "communications",
        ),
    ),
)
